// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Absen;
import com.rpll.app.model.AbsenDataOnDemand;
import com.rpll.app.model.AbsenIntegrationTest;
import com.rpll.app.model.AbsenPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AbsenIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AbsenIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AbsenIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AbsenIntegrationTest: @Transactional;
    
    @Autowired
    private AbsenDataOnDemand AbsenIntegrationTest.dod;
    
    @Test
    public void AbsenIntegrationTest.testCountAbsens() {
        Assert.assertNotNull("Data on demand for 'Absen' failed to initialize correctly", dod.getRandomAbsen());
        long count = Absen.countAbsens();
        Assert.assertTrue("Counter for 'Absen' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AbsenIntegrationTest.testFindAbsen() {
        Absen obj = dod.getRandomAbsen();
        Assert.assertNotNull("Data on demand for 'Absen' failed to initialize correctly", obj);
        AbsenPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Absen' failed to provide an identifier", id);
        obj = Absen.findAbsen(id);
        Assert.assertNotNull("Find method for 'Absen' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Absen' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AbsenIntegrationTest.testFindAllAbsens() {
        Assert.assertNotNull("Data on demand for 'Absen' failed to initialize correctly", dod.getRandomAbsen());
        long count = Absen.countAbsens();
        Assert.assertTrue("Too expensive to perform a find all test for 'Absen', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Absen> result = Absen.findAllAbsens();
        Assert.assertNotNull("Find all method for 'Absen' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Absen' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AbsenIntegrationTest.testFindAbsenEntries() {
        Assert.assertNotNull("Data on demand for 'Absen' failed to initialize correctly", dod.getRandomAbsen());
        long count = Absen.countAbsens();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Absen> result = Absen.findAbsenEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Absen' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Absen' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AbsenIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Absen' failed to initialize correctly", dod.getRandomAbsen());
        Absen obj = dod.getNewTransientAbsen(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Absen' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Absen' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AbsenIntegrationTest.testRemove() {
        Absen obj = dod.getRandomAbsen();
        Assert.assertNotNull("Data on demand for 'Absen' failed to initialize correctly", obj);
        AbsenPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Absen' failed to provide an identifier", id);
        obj = Absen.findAbsen(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Absen' with identifier '" + id + "'", Absen.findAbsen(id));
    }
    
}
