// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.BahanKuliah;
import com.rpll.app.model.BahanKuliahDataOnDemand;
import com.rpll.app.model.BahanKuliahIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BahanKuliahIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BahanKuliahIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BahanKuliahIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BahanKuliahIntegrationTest: @Transactional;
    
    @Autowired
    private BahanKuliahDataOnDemand BahanKuliahIntegrationTest.dod;
    
    @Test
    public void BahanKuliahIntegrationTest.testCountBahanKuliahs() {
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to initialize correctly", dod.getRandomBahanKuliah());
        long count = BahanKuliah.countBahanKuliahs();
        Assert.assertTrue("Counter for 'BahanKuliah' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BahanKuliahIntegrationTest.testFindBahanKuliah() {
        BahanKuliah obj = dod.getRandomBahanKuliah();
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to initialize correctly", obj);
        String id = obj.getKodeBahan();
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to provide an identifier", id);
        obj = BahanKuliah.findBahanKuliah(id);
        Assert.assertNotNull("Find method for 'BahanKuliah' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BahanKuliah' returned the incorrect identifier", id, obj.getKodeBahan());
    }
    
    @Test
    public void BahanKuliahIntegrationTest.testFindAllBahanKuliahs() {
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to initialize correctly", dod.getRandomBahanKuliah());
        long count = BahanKuliah.countBahanKuliahs();
        Assert.assertTrue("Too expensive to perform a find all test for 'BahanKuliah', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BahanKuliah> result = BahanKuliah.findAllBahanKuliahs();
        Assert.assertNotNull("Find all method for 'BahanKuliah' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BahanKuliah' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BahanKuliahIntegrationTest.testFindBahanKuliahEntries() {
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to initialize correctly", dod.getRandomBahanKuliah());
        long count = BahanKuliah.countBahanKuliahs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BahanKuliah> result = BahanKuliah.findBahanKuliahEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BahanKuliah' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BahanKuliah' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BahanKuliahIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to initialize correctly", dod.getRandomBahanKuliah());
        BahanKuliah obj = dod.getNewTransientBahanKuliah(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BahanKuliah' identifier to be null", obj.getKodeBahan());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BahanKuliah' identifier to no longer be null", obj.getKodeBahan());
    }
    
    @Test
    public void BahanKuliahIntegrationTest.testRemove() {
        BahanKuliah obj = dod.getRandomBahanKuliah();
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to initialize correctly", obj);
        String id = obj.getKodeBahan();
        Assert.assertNotNull("Data on demand for 'BahanKuliah' failed to provide an identifier", id);
        obj = BahanKuliah.findBahanKuliah(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BahanKuliah' with identifier '" + id + "'", BahanKuliah.findBahanKuliah(id));
    }
    
}
