// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Biaya;
import com.rpll.app.model.BiayaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BiayaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BiayaDataOnDemand: @Component;
    
    private Random BiayaDataOnDemand.rnd = new SecureRandom();
    
    private List<Biaya> BiayaDataOnDemand.data;
    
    public Biaya BiayaDataOnDemand.getNewTransientBiaya(int index) {
        Biaya obj = new Biaya();
        setBiayaMhs(obj, index);
        setBiayaPraktikum(obj, index);
        setBiayaSks(obj, index);
        setBiayaTetap(obj, index);
        return obj;
    }
    
    public void BiayaDataOnDemand.setBiayaMhs(Biaya obj, int index) {
        Integer biayaMhs = new Integer(index);
        obj.setBiayaMhs(biayaMhs);
    }
    
    public void BiayaDataOnDemand.setBiayaPraktikum(Biaya obj, int index) {
        Integer biayaPraktikum = new Integer(index);
        obj.setBiayaPraktikum(biayaPraktikum);
    }
    
    public void BiayaDataOnDemand.setBiayaSks(Biaya obj, int index) {
        Integer biayaSks = new Integer(index);
        obj.setBiayaSks(biayaSks);
    }
    
    public void BiayaDataOnDemand.setBiayaTetap(Biaya obj, int index) {
        Integer biayaTetap = new Integer(index);
        obj.setBiayaTetap(biayaTetap);
    }
    
    public Biaya BiayaDataOnDemand.getSpecificBiaya(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Biaya obj = data.get(index);
        String id = obj.getKodeBiaya();
        return Biaya.findBiaya(id);
    }
    
    public Biaya BiayaDataOnDemand.getRandomBiaya() {
        init();
        Biaya obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getKodeBiaya();
        return Biaya.findBiaya(id);
    }
    
    public boolean BiayaDataOnDemand.modifyBiaya(Biaya obj) {
        return false;
    }
    
    public void BiayaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Biaya.findBiayaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Biaya' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Biaya>();
        for (int i = 0; i < 10; i++) {
            Biaya obj = getNewTransientBiaya(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
