// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Departemen;
import com.rpll.app.model.DepartemenDataOnDemand;
import com.rpll.app.model.FakultasDataOnDemand;
import com.rpll.app.model.PegawaiDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DepartemenDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DepartemenDataOnDemand: @Component;
    
    private Random DepartemenDataOnDemand.rnd = new SecureRandom();
    
    private List<Departemen> DepartemenDataOnDemand.data;
    
    @Autowired
    private FakultasDataOnDemand DepartemenDataOnDemand.fakultasDataOnDemand;
    
    @Autowired
    private PegawaiDataOnDemand DepartemenDataOnDemand.pegawaiDataOnDemand;
    
    public Departemen DepartemenDataOnDemand.getNewTransientDepartemen(int index) {
        Departemen obj = new Departemen();
        setNamaDepart(obj, index);
        return obj;
    }
    
    public void DepartemenDataOnDemand.setNamaDepart(Departemen obj, int index) {
        String namaDepart = "namaDepart_" + index;
        if (namaDepart.length() > 40) {
            namaDepart = namaDepart.substring(0, 40);
        }
        obj.setNamaDepart(namaDepart);
    }
    
    public Departemen DepartemenDataOnDemand.getSpecificDepartemen(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Departemen obj = data.get(index);
        String id = obj.getKodeDepart();
        return Departemen.findDepartemen(id);
    }
    
    public Departemen DepartemenDataOnDemand.getRandomDepartemen() {
        init();
        Departemen obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getKodeDepart();
        return Departemen.findDepartemen(id);
    }
    
    public boolean DepartemenDataOnDemand.modifyDepartemen(Departemen obj) {
        return false;
    }
    
    public void DepartemenDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Departemen.findDepartemenEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Departemen' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Departemen>();
        for (int i = 0; i < 10; i++) {
            Departemen obj = getNewTransientDepartemen(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
