// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.FakultasDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FakultasDataOnDemand_Roo_Configurable {
    
    declare @type: FakultasDataOnDemand: @Configurable;
    
}
