// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Fasilitas;
import com.rpll.app.model.FasilitasDataOnDemand;
import com.rpll.app.model.FasilitasIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FasilitasIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FasilitasIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FasilitasIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FasilitasIntegrationTest: @Transactional;
    
    @Autowired
    private FasilitasDataOnDemand FasilitasIntegrationTest.dod;
    
    @Test
    public void FasilitasIntegrationTest.testCountFasilitases() {
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to initialize correctly", dod.getRandomFasilitas());
        long count = Fasilitas.countFasilitases();
        Assert.assertTrue("Counter for 'Fasilitas' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FasilitasIntegrationTest.testFindFasilitas() {
        Fasilitas obj = dod.getRandomFasilitas();
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to initialize correctly", obj);
        String id = obj.getKodeFasilitas();
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to provide an identifier", id);
        obj = Fasilitas.findFasilitas(id);
        Assert.assertNotNull("Find method for 'Fasilitas' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Fasilitas' returned the incorrect identifier", id, obj.getKodeFasilitas());
    }
    
    @Test
    public void FasilitasIntegrationTest.testFindAllFasilitases() {
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to initialize correctly", dod.getRandomFasilitas());
        long count = Fasilitas.countFasilitases();
        Assert.assertTrue("Too expensive to perform a find all test for 'Fasilitas', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Fasilitas> result = Fasilitas.findAllFasilitases();
        Assert.assertNotNull("Find all method for 'Fasilitas' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Fasilitas' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FasilitasIntegrationTest.testFindFasilitasEntries() {
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to initialize correctly", dod.getRandomFasilitas());
        long count = Fasilitas.countFasilitases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Fasilitas> result = Fasilitas.findFasilitasEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Fasilitas' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Fasilitas' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FasilitasIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to initialize correctly", dod.getRandomFasilitas());
        Fasilitas obj = dod.getNewTransientFasilitas(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Fasilitas' identifier to be null", obj.getKodeFasilitas());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Fasilitas' identifier to no longer be null", obj.getKodeFasilitas());
    }
    
    @Test
    public void FasilitasIntegrationTest.testRemove() {
        Fasilitas obj = dod.getRandomFasilitas();
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to initialize correctly", obj);
        String id = obj.getKodeFasilitas();
        Assert.assertNotNull("Data on demand for 'Fasilitas' failed to provide an identifier", id);
        obj = Fasilitas.findFasilitas(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Fasilitas' with identifier '" + id + "'", Fasilitas.findFasilitas(id));
    }
    
}
