// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Frs;
import com.rpll.app.model.FrsDataOnDemand;
import com.rpll.app.model.FrsPK;
import com.rpll.app.model.MahasiswaDataOnDemand;
import com.rpll.app.model.MataKuliahDataOnDemand;
import com.rpll.app.model.PegawaiDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FrsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FrsDataOnDemand: @Component;
    
    private Random FrsDataOnDemand.rnd = new SecureRandom();
    
    private List<Frs> FrsDataOnDemand.data;
    
    @Autowired
    private MataKuliahDataOnDemand FrsDataOnDemand.mataKuliahDataOnDemand;
    
    @Autowired
    private MahasiswaDataOnDemand FrsDataOnDemand.mahasiswaDataOnDemand;
    
    @Autowired
    private PegawaiDataOnDemand FrsDataOnDemand.pegawaiDataOnDemand;
    
    public Frs FrsDataOnDemand.getNewTransientFrs(int index) {
        Frs obj = new Frs();
        setEmbeddedIdClass(obj, index);
        setStatusValid(obj, index);
        return obj;
    }
    
    public void FrsDataOnDemand.setEmbeddedIdClass(Frs obj, int index) {
        String nim = "nim_" + index;
        if (nim.length() > 20) {
            nim = new Random().nextInt(10) + nim.substring(1, 20);
        }
        String kodeMatkul = "kodeMatkul_" + index;
        if (kodeMatkul.length() > 20) {
            kodeMatkul = new Random().nextInt(10) + kodeMatkul.substring(1, 20);
        }
        String nip = "nip_" + index;
        if (nip.length() > 20) {
            nip = new Random().nextInt(10) + nip.substring(1, 20);
        }
        
        FrsPK embeddedIdClass = new FrsPK(nim, kodeMatkul, nip);
        obj.setId(embeddedIdClass);
    }
    
    public void FrsDataOnDemand.setStatusValid(Frs obj, int index) {
        String statusValid = "statusValid_" + index;
        if (statusValid.length() > 20) {
            statusValid = statusValid.substring(0, 20);
        }
        obj.setStatusValid(statusValid);
    }
    
    public Frs FrsDataOnDemand.getSpecificFrs(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Frs obj = data.get(index);
        FrsPK id = obj.getId();
        return Frs.findFrs(id);
    }
    
    public Frs FrsDataOnDemand.getRandomFrs() {
        init();
        Frs obj = data.get(rnd.nextInt(data.size()));
        FrsPK id = obj.getId();
        return Frs.findFrs(id);
    }
    
    public boolean FrsDataOnDemand.modifyFrs(Frs obj) {
        return false;
    }
    
    public void FrsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Frs.findFrsEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Frs' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Frs>();
        for (int i = 0; i < 10; i++) {
            Frs obj = getNewTransientFrs(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
