// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.HakAkses;
import com.rpll.app.model.HakAksesDataOnDemand;
import com.rpll.app.model.HakAksesIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HakAksesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HakAksesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HakAksesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HakAksesIntegrationTest: @Transactional;
    
    @Autowired
    private HakAksesDataOnDemand HakAksesIntegrationTest.dod;
    
    @Test
    public void HakAksesIntegrationTest.testCountHakAkseses() {
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to initialize correctly", dod.getRandomHakAkses());
        long count = HakAkses.countHakAkseses();
        Assert.assertTrue("Counter for 'HakAkses' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HakAksesIntegrationTest.testFindHakAkses() {
        HakAkses obj = dod.getRandomHakAkses();
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to initialize correctly", obj);
        String id = obj.getKodeAkses();
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to provide an identifier", id);
        obj = HakAkses.findHakAkses(id);
        Assert.assertNotNull("Find method for 'HakAkses' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HakAkses' returned the incorrect identifier", id, obj.getKodeAkses());
    }
    
    @Test
    public void HakAksesIntegrationTest.testFindAllHakAkseses() {
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to initialize correctly", dod.getRandomHakAkses());
        long count = HakAkses.countHakAkseses();
        Assert.assertTrue("Too expensive to perform a find all test for 'HakAkses', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HakAkses> result = HakAkses.findAllHakAkseses();
        Assert.assertNotNull("Find all method for 'HakAkses' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HakAkses' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HakAksesIntegrationTest.testFindHakAksesEntries() {
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to initialize correctly", dod.getRandomHakAkses());
        long count = HakAkses.countHakAkseses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HakAkses> result = HakAkses.findHakAksesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HakAkses' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HakAkses' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HakAksesIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to initialize correctly", dod.getRandomHakAkses());
        HakAkses obj = dod.getNewTransientHakAkses(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HakAkses' identifier to be null", obj.getKodeAkses());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HakAkses' identifier to no longer be null", obj.getKodeAkses());
    }
    
    @Test
    public void HakAksesIntegrationTest.testRemove() {
        HakAkses obj = dod.getRandomHakAkses();
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to initialize correctly", obj);
        String id = obj.getKodeAkses();
        Assert.assertNotNull("Data on demand for 'HakAkses' failed to provide an identifier", id);
        obj = HakAkses.findHakAkses(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HakAkses' with identifier '" + id + "'", HakAkses.findHakAkses(id));
    }
    
}
