// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Kelas;
import com.rpll.app.model.KelasDataOnDemand;
import com.rpll.app.model.KelasIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect KelasIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KelasIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KelasIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: KelasIntegrationTest: @Transactional;
    
    @Autowired
    private KelasDataOnDemand KelasIntegrationTest.dod;
    
    @Test
    public void KelasIntegrationTest.testCountKelases() {
        Assert.assertNotNull("Data on demand for 'Kelas' failed to initialize correctly", dod.getRandomKelas());
        long count = Kelas.countKelases();
        Assert.assertTrue("Counter for 'Kelas' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KelasIntegrationTest.testFindKelas() {
        Kelas obj = dod.getRandomKelas();
        Assert.assertNotNull("Data on demand for 'Kelas' failed to initialize correctly", obj);
        String id = obj.getKodeKelas();
        Assert.assertNotNull("Data on demand for 'Kelas' failed to provide an identifier", id);
        obj = Kelas.findKelas(id);
        Assert.assertNotNull("Find method for 'Kelas' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Kelas' returned the incorrect identifier", id, obj.getKodeKelas());
    }
    
    @Test
    public void KelasIntegrationTest.testFindAllKelases() {
        Assert.assertNotNull("Data on demand for 'Kelas' failed to initialize correctly", dod.getRandomKelas());
        long count = Kelas.countKelases();
        Assert.assertTrue("Too expensive to perform a find all test for 'Kelas', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Kelas> result = Kelas.findAllKelases();
        Assert.assertNotNull("Find all method for 'Kelas' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Kelas' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KelasIntegrationTest.testFindKelasEntries() {
        Assert.assertNotNull("Data on demand for 'Kelas' failed to initialize correctly", dod.getRandomKelas());
        long count = Kelas.countKelases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Kelas> result = Kelas.findKelasEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Kelas' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Kelas' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KelasIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Kelas' failed to initialize correctly", dod.getRandomKelas());
        Kelas obj = dod.getNewTransientKelas(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Kelas' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Kelas' identifier to be null", obj.getKodeKelas());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Kelas' identifier to no longer be null", obj.getKodeKelas());
    }
    
    @Test
    public void KelasIntegrationTest.testRemove() {
        Kelas obj = dod.getRandomKelas();
        Assert.assertNotNull("Data on demand for 'Kelas' failed to initialize correctly", obj);
        String id = obj.getKodeKelas();
        Assert.assertNotNull("Data on demand for 'Kelas' failed to provide an identifier", id);
        obj = Kelas.findKelas(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Kelas' with identifier '" + id + "'", Kelas.findKelas(id));
    }
    
}
