// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.KritikSaran;
import com.rpll.app.model.KritikSaranDataOnDemand;
import com.rpll.app.model.KritikSaranIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect KritikSaranIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KritikSaranIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KritikSaranIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: KritikSaranIntegrationTest: @Transactional;
    
    @Autowired
    private KritikSaranDataOnDemand KritikSaranIntegrationTest.dod;
    
    @Test
    public void KritikSaranIntegrationTest.testCountKritikSarans() {
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to initialize correctly", dod.getRandomKritikSaran());
        long count = KritikSaran.countKritikSarans();
        Assert.assertTrue("Counter for 'KritikSaran' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KritikSaranIntegrationTest.testFindKritikSaran() {
        KritikSaran obj = dod.getRandomKritikSaran();
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to initialize correctly", obj);
        String id = obj.getKodeKritik();
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to provide an identifier", id);
        obj = KritikSaran.findKritikSaran(id);
        Assert.assertNotNull("Find method for 'KritikSaran' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'KritikSaran' returned the incorrect identifier", id, obj.getKodeKritik());
    }
    
    @Test
    public void KritikSaranIntegrationTest.testFindAllKritikSarans() {
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to initialize correctly", dod.getRandomKritikSaran());
        long count = KritikSaran.countKritikSarans();
        Assert.assertTrue("Too expensive to perform a find all test for 'KritikSaran', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<KritikSaran> result = KritikSaran.findAllKritikSarans();
        Assert.assertNotNull("Find all method for 'KritikSaran' illegally returned null", result);
        Assert.assertTrue("Find all method for 'KritikSaran' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KritikSaranIntegrationTest.testFindKritikSaranEntries() {
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to initialize correctly", dod.getRandomKritikSaran());
        long count = KritikSaran.countKritikSarans();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<KritikSaran> result = KritikSaran.findKritikSaranEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'KritikSaran' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'KritikSaran' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KritikSaranIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to initialize correctly", dod.getRandomKritikSaran());
        KritikSaran obj = dod.getNewTransientKritikSaran(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'KritikSaran' identifier to be null", obj.getKodeKritik());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'KritikSaran' identifier to no longer be null", obj.getKodeKritik());
    }
    
    @Test
    public void KritikSaranIntegrationTest.testRemove() {
        KritikSaran obj = dod.getRandomKritikSaran();
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to initialize correctly", obj);
        String id = obj.getKodeKritik();
        Assert.assertNotNull("Data on demand for 'KritikSaran' failed to provide an identifier", id);
        obj = KritikSaran.findKritikSaran(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'KritikSaran' with identifier '" + id + "'", KritikSaran.findKritikSaran(id));
    }
    
}
