// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.KritikSaran;
import com.rpll.app.model.KritikSaranDataOnDemand;
import com.rpll.app.model.MahasiswaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect KritikSaranDataOnDemand_Roo_DataOnDemand {
    
    declare @type: KritikSaranDataOnDemand: @Component;
    
    private Random KritikSaranDataOnDemand.rnd = new SecureRandom();
    
    private List<KritikSaran> KritikSaranDataOnDemand.data;
    
    @Autowired
    private MahasiswaDataOnDemand KritikSaranDataOnDemand.mahasiswaDataOnDemand;
    
    public KritikSaran KritikSaranDataOnDemand.getNewTransientKritikSaran(int index) {
        KritikSaran obj = new KritikSaran();
        setIsiKritik(obj, index);
        return obj;
    }
    
    public void KritikSaranDataOnDemand.setIsiKritik(KritikSaran obj, int index) {
        String isiKritik = "isiKritik_" + index;
        if (isiKritik.length() > 300) {
            isiKritik = isiKritik.substring(0, 300);
        }
        obj.setIsiKritik(isiKritik);
    }
    
    public KritikSaran KritikSaranDataOnDemand.getSpecificKritikSaran(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        KritikSaran obj = data.get(index);
        String id = obj.getKodeKritik();
        return KritikSaran.findKritikSaran(id);
    }
    
    public KritikSaran KritikSaranDataOnDemand.getRandomKritikSaran() {
        init();
        KritikSaran obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getKodeKritik();
        return KritikSaran.findKritikSaran(id);
    }
    
    public boolean KritikSaranDataOnDemand.modifyKritikSaran(KritikSaran obj) {
        return false;
    }
    
    public void KritikSaranDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = KritikSaran.findKritikSaranEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'KritikSaran' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<KritikSaran>();
        for (int i = 0; i < 10; i++) {
            KritikSaran obj = getNewTransientKritikSaran(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
