// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.MataKuliah;
import com.rpll.app.model.MataKuliahDataOnDemand;
import com.rpll.app.model.MataKuliahIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MataKuliahIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MataKuliahIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MataKuliahIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MataKuliahIntegrationTest: @Transactional;
    
    @Autowired
    private MataKuliahDataOnDemand MataKuliahIntegrationTest.dod;
    
    @Test
    public void MataKuliahIntegrationTest.testCountMataKuliahs() {
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to initialize correctly", dod.getRandomMataKuliah());
        long count = MataKuliah.countMataKuliahs();
        Assert.assertTrue("Counter for 'MataKuliah' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MataKuliahIntegrationTest.testFindMataKuliah() {
        MataKuliah obj = dod.getRandomMataKuliah();
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to initialize correctly", obj);
        String id = obj.getKodeMatkul();
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to provide an identifier", id);
        obj = MataKuliah.findMataKuliah(id);
        Assert.assertNotNull("Find method for 'MataKuliah' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MataKuliah' returned the incorrect identifier", id, obj.getKodeMatkul());
    }
    
    @Test
    public void MataKuliahIntegrationTest.testFindAllMataKuliahs() {
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to initialize correctly", dod.getRandomMataKuliah());
        long count = MataKuliah.countMataKuliahs();
        Assert.assertTrue("Too expensive to perform a find all test for 'MataKuliah', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MataKuliah> result = MataKuliah.findAllMataKuliahs();
        Assert.assertNotNull("Find all method for 'MataKuliah' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MataKuliah' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MataKuliahIntegrationTest.testFindMataKuliahEntries() {
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to initialize correctly", dod.getRandomMataKuliah());
        long count = MataKuliah.countMataKuliahs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MataKuliah> result = MataKuliah.findMataKuliahEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MataKuliah' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MataKuliah' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MataKuliahIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to initialize correctly", dod.getRandomMataKuliah());
        MataKuliah obj = dod.getNewTransientMataKuliah(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MataKuliah' identifier to be null", obj.getKodeMatkul());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MataKuliah' identifier to no longer be null", obj.getKodeMatkul());
    }
    
    @Test
    public void MataKuliahIntegrationTest.testRemove() {
        MataKuliah obj = dod.getRandomMataKuliah();
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to initialize correctly", obj);
        String id = obj.getKodeMatkul();
        Assert.assertNotNull("Data on demand for 'MataKuliah' failed to provide an identifier", id);
        obj = MataKuliah.findMataKuliah(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MataKuliah' with identifier '" + id + "'", MataKuliah.findMataKuliah(id));
    }
    
}
