// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Nilai;
import com.rpll.app.model.NilaiDataOnDemand;
import com.rpll.app.model.NilaiIntegrationTest;
import com.rpll.app.model.NilaiPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NilaiIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NilaiIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NilaiIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NilaiIntegrationTest: @Transactional;
    
    @Autowired
    private NilaiDataOnDemand NilaiIntegrationTest.dod;
    
    @Test
    public void NilaiIntegrationTest.testCountNilais() {
        Assert.assertNotNull("Data on demand for 'Nilai' failed to initialize correctly", dod.getRandomNilai());
        long count = Nilai.countNilais();
        Assert.assertTrue("Counter for 'Nilai' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NilaiIntegrationTest.testFindNilai() {
        Nilai obj = dod.getRandomNilai();
        Assert.assertNotNull("Data on demand for 'Nilai' failed to initialize correctly", obj);
        NilaiPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nilai' failed to provide an identifier", id);
        obj = Nilai.findNilai(id);
        Assert.assertNotNull("Find method for 'Nilai' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Nilai' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NilaiIntegrationTest.testFindAllNilais() {
        Assert.assertNotNull("Data on demand for 'Nilai' failed to initialize correctly", dod.getRandomNilai());
        long count = Nilai.countNilais();
        Assert.assertTrue("Too expensive to perform a find all test for 'Nilai', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Nilai> result = Nilai.findAllNilais();
        Assert.assertNotNull("Find all method for 'Nilai' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Nilai' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NilaiIntegrationTest.testFindNilaiEntries() {
        Assert.assertNotNull("Data on demand for 'Nilai' failed to initialize correctly", dod.getRandomNilai());
        long count = Nilai.countNilais();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Nilai> result = Nilai.findNilaiEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Nilai' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Nilai' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NilaiIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Nilai' failed to initialize correctly", dod.getRandomNilai());
        Nilai obj = dod.getNewTransientNilai(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Nilai' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Nilai' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NilaiIntegrationTest.testRemove() {
        Nilai obj = dod.getRandomNilai();
        Assert.assertNotNull("Data on demand for 'Nilai' failed to initialize correctly", obj);
        NilaiPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nilai' failed to provide an identifier", id);
        obj = Nilai.findNilai(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Nilai' with identifier '" + id + "'", Nilai.findNilai(id));
    }
    
}
