// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Pegawai;
import com.rpll.app.model.PegawaiDataOnDemand;
import com.rpll.app.model.PegawaiIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PegawaiIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PegawaiIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PegawaiIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PegawaiIntegrationTest: @Transactional;
    
    @Autowired
    private PegawaiDataOnDemand PegawaiIntegrationTest.dod;
    
    @Test
    public void PegawaiIntegrationTest.testCountPegawais() {
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to initialize correctly", dod.getRandomPegawai());
        long count = Pegawai.countPegawais();
        Assert.assertTrue("Counter for 'Pegawai' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PegawaiIntegrationTest.testFindPegawai() {
        Pegawai obj = dod.getRandomPegawai();
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to initialize correctly", obj);
        String id = obj.getNip();
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to provide an identifier", id);
        obj = Pegawai.findPegawai(id);
        Assert.assertNotNull("Find method for 'Pegawai' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Pegawai' returned the incorrect identifier", id, obj.getNip());
    }
    
    @Test
    public void PegawaiIntegrationTest.testFindAllPegawais() {
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to initialize correctly", dod.getRandomPegawai());
        long count = Pegawai.countPegawais();
        Assert.assertTrue("Too expensive to perform a find all test for 'Pegawai', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Pegawai> result = Pegawai.findAllPegawais();
        Assert.assertNotNull("Find all method for 'Pegawai' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Pegawai' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PegawaiIntegrationTest.testFindPegawaiEntries() {
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to initialize correctly", dod.getRandomPegawai());
        long count = Pegawai.countPegawais();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Pegawai> result = Pegawai.findPegawaiEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Pegawai' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Pegawai' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PegawaiIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to initialize correctly", dod.getRandomPegawai());
        Pegawai obj = dod.getNewTransientPegawai(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Pegawai' identifier to be null", obj.getNip());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Pegawai' identifier to no longer be null", obj.getNip());
    }
    
    @Test
    public void PegawaiIntegrationTest.testRemove() {
        Pegawai obj = dod.getRandomPegawai();
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to initialize correctly", obj);
        String id = obj.getNip();
        Assert.assertNotNull("Data on demand for 'Pegawai' failed to provide an identifier", id);
        obj = Pegawai.findPegawai(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Pegawai' with identifier '" + id + "'", Pegawai.findPegawai(id));
    }
    
}
