// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.DepartemenDataOnDemand;
import com.rpll.app.model.Pengumuman;
import com.rpll.app.model.PengumumanDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PengumumanDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PengumumanDataOnDemand: @Component;
    
    private Random PengumumanDataOnDemand.rnd = new SecureRandom();
    
    private List<Pengumuman> PengumumanDataOnDemand.data;
    
    @Autowired
    private DepartemenDataOnDemand PengumumanDataOnDemand.departemenDataOnDemand;
    
    public Pengumuman PengumumanDataOnDemand.getNewTransientPengumuman(int index) {
        Pengumuman obj = new Pengumuman();
        setIsi(obj, index);
        setJudul(obj, index);
        return obj;
    }
    
    public void PengumumanDataOnDemand.setIsi(Pengumuman obj, int index) {
        String isi = "isi_" + index;
        if (isi.length() > 300) {
            isi = isi.substring(0, 300);
        }
        obj.setIsi(isi);
    }
    
    public void PengumumanDataOnDemand.setJudul(Pengumuman obj, int index) {
        String judul = "judul_" + index;
        if (judul.length() > 40) {
            judul = judul.substring(0, 40);
        }
        obj.setJudul(judul);
    }
    
    public Pengumuman PengumumanDataOnDemand.getSpecificPengumuman(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Pengumuman obj = data.get(index);
        String id = obj.getKodePengumuman();
        return Pengumuman.findPengumuman(id);
    }
    
    public Pengumuman PengumumanDataOnDemand.getRandomPengumuman() {
        init();
        Pengumuman obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getKodePengumuman();
        return Pengumuman.findPengumuman(id);
    }
    
    public boolean PengumumanDataOnDemand.modifyPengumuman(Pengumuman obj) {
        return false;
    }
    
    public void PengumumanDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Pengumuman.findPengumumanEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Pengumuman' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Pengumuman>();
        for (int i = 0; i < 10; i++) {
            Pengumuman obj = getNewTransientPengumuman(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
