// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Pengumuman;
import com.rpll.app.model.PengumumanDataOnDemand;
import com.rpll.app.model.PengumumanIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PengumumanIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PengumumanIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PengumumanIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PengumumanIntegrationTest: @Transactional;
    
    @Autowired
    private PengumumanDataOnDemand PengumumanIntegrationTest.dod;
    
    @Test
    public void PengumumanIntegrationTest.testCountPengumumen() {
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to initialize correctly", dod.getRandomPengumuman());
        long count = Pengumuman.countPengumumen();
        Assert.assertTrue("Counter for 'Pengumuman' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PengumumanIntegrationTest.testFindPengumuman() {
        Pengumuman obj = dod.getRandomPengumuman();
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to initialize correctly", obj);
        String id = obj.getKodePengumuman();
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to provide an identifier", id);
        obj = Pengumuman.findPengumuman(id);
        Assert.assertNotNull("Find method for 'Pengumuman' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Pengumuman' returned the incorrect identifier", id, obj.getKodePengumuman());
    }
    
    @Test
    public void PengumumanIntegrationTest.testFindAllPengumumen() {
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to initialize correctly", dod.getRandomPengumuman());
        long count = Pengumuman.countPengumumen();
        Assert.assertTrue("Too expensive to perform a find all test for 'Pengumuman', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Pengumuman> result = Pengumuman.findAllPengumumen();
        Assert.assertNotNull("Find all method for 'Pengumuman' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Pengumuman' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PengumumanIntegrationTest.testFindPengumumanEntries() {
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to initialize correctly", dod.getRandomPengumuman());
        long count = Pengumuman.countPengumumen();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Pengumuman> result = Pengumuman.findPengumumanEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Pengumuman' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Pengumuman' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PengumumanIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to initialize correctly", dod.getRandomPengumuman());
        Pengumuman obj = dod.getNewTransientPengumuman(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Pengumuman' identifier to be null", obj.getKodePengumuman());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Pengumuman' identifier to no longer be null", obj.getKodePengumuman());
    }
    
    @Test
    public void PengumumanIntegrationTest.testRemove() {
        Pengumuman obj = dod.getRandomPengumuman();
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to initialize correctly", obj);
        String id = obj.getKodePengumuman();
        Assert.assertNotNull("Data on demand for 'Pengumuman' failed to provide an identifier", id);
        obj = Pengumuman.findPengumuman(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Pengumuman' with identifier '" + id + "'", Pengumuman.findPengumuman(id));
    }
    
}
