// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.Staff;
import com.rpll.app.model.StaffDataOnDemand;
import com.rpll.app.model.StaffIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StaffIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StaffIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StaffIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StaffIntegrationTest: @Transactional;
    
    @Autowired
    private StaffDataOnDemand StaffIntegrationTest.dod;
    
    @Test
    public void StaffIntegrationTest.testCountStaffs() {
        Assert.assertNotNull("Data on demand for 'Staff' failed to initialize correctly", dod.getRandomStaff());
        long count = Staff.countStaffs();
        Assert.assertTrue("Counter for 'Staff' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StaffIntegrationTest.testFindStaff() {
        Staff obj = dod.getRandomStaff();
        Assert.assertNotNull("Data on demand for 'Staff' failed to initialize correctly", obj);
        String id = obj.getNip();
        Assert.assertNotNull("Data on demand for 'Staff' failed to provide an identifier", id);
        obj = Staff.findStaff(id);
        Assert.assertNotNull("Find method for 'Staff' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Staff' returned the incorrect identifier", id, obj.getNip());
    }
    
    @Test
    public void StaffIntegrationTest.testFindAllStaffs() {
        Assert.assertNotNull("Data on demand for 'Staff' failed to initialize correctly", dod.getRandomStaff());
        long count = Staff.countStaffs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Staff', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Staff> result = Staff.findAllStaffs();
        Assert.assertNotNull("Find all method for 'Staff' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Staff' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StaffIntegrationTest.testFindStaffEntries() {
        Assert.assertNotNull("Data on demand for 'Staff' failed to initialize correctly", dod.getRandomStaff());
        long count = Staff.countStaffs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Staff> result = Staff.findStaffEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Staff' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Staff' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StaffIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Staff' failed to initialize correctly", dod.getRandomStaff());
        Staff obj = dod.getNewTransientStaff(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Staff' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Staff' identifier to be null", obj.getNip());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Staff' identifier to no longer be null", obj.getNip());
    }
    
    @Test
    public void StaffIntegrationTest.testRemove() {
        Staff obj = dod.getRandomStaff();
        Assert.assertNotNull("Data on demand for 'Staff' failed to initialize correctly", obj);
        String id = obj.getNip();
        Assert.assertNotNull("Data on demand for 'Staff' failed to provide an identifier", id);
        obj = Staff.findStaff(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Staff' with identifier '" + id + "'", Staff.findStaff(id));
    }
    
}
