// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.TanggungJawab;
import com.rpll.app.model.TanggungJawabDataOnDemand;
import com.rpll.app.model.TanggungJawabIntegrationTest;
import com.rpll.app.model.TanggungJawabPK;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TanggungJawabIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TanggungJawabIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TanggungJawabIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TanggungJawabIntegrationTest: @Transactional;
    
    @Autowired
    private TanggungJawabDataOnDemand TanggungJawabIntegrationTest.dod;
    
    @Test
    public void TanggungJawabIntegrationTest.testCountTanggungJawabs() {
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to initialize correctly", dod.getRandomTanggungJawab());
        long count = TanggungJawab.countTanggungJawabs();
        Assert.assertTrue("Counter for 'TanggungJawab' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TanggungJawabIntegrationTest.testFindTanggungJawab() {
        TanggungJawab obj = dod.getRandomTanggungJawab();
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to initialize correctly", obj);
        TanggungJawabPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to provide an identifier", id);
        obj = TanggungJawab.findTanggungJawab(id);
        Assert.assertNotNull("Find method for 'TanggungJawab' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TanggungJawab' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TanggungJawabIntegrationTest.testFindAllTanggungJawabs() {
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to initialize correctly", dod.getRandomTanggungJawab());
        long count = TanggungJawab.countTanggungJawabs();
        Assert.assertTrue("Too expensive to perform a find all test for 'TanggungJawab', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TanggungJawab> result = TanggungJawab.findAllTanggungJawabs();
        Assert.assertNotNull("Find all method for 'TanggungJawab' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TanggungJawab' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TanggungJawabIntegrationTest.testFindTanggungJawabEntries() {
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to initialize correctly", dod.getRandomTanggungJawab());
        long count = TanggungJawab.countTanggungJawabs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TanggungJawab> result = TanggungJawab.findTanggungJawabEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TanggungJawab' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TanggungJawab' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TanggungJawabIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to initialize correctly", dod.getRandomTanggungJawab());
        TanggungJawab obj = dod.getNewTransientTanggungJawab(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to provide a new transient entity", obj);
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TanggungJawab' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TanggungJawabIntegrationTest.testRemove() {
        TanggungJawab obj = dod.getRandomTanggungJawab();
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to initialize correctly", obj);
        TanggungJawabPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TanggungJawab' failed to provide an identifier", id);
        obj = TanggungJawab.findTanggungJawab(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TanggungJawab' with identifier '" + id + "'", TanggungJawab.findTanggungJawab(id));
    }
    
}
