// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.AbsenPK;
import java.io.Serializable;

privileged aspect AbsenPK_Roo_Serializable {
    
    declare parents: AbsenPK implements Serializable;
    
    private static final long AbsenPK.serialVersionUID = 1L;
    
}
