// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.FrsPK;
import java.io.Serializable;

privileged aspect FrsPK_Roo_Serializable {
    
    declare parents: FrsPK implements Serializable;
    
    private static final long FrsPK.serialVersionUID = 1L;
    
}
