// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.JadwalPK;
import java.io.Serializable;

privileged aspect JadwalPK_Roo_Serializable {
    
    declare parents: JadwalPK implements Serializable;
    
    private static final long JadwalPK.serialVersionUID = 1L;
    
}
