// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rpll.app.model;

import com.rpll.app.model.TanggungJawabPK;
import java.io.Serializable;

privileged aspect TanggungJawabPK_Roo_Serializable {
    
    declare parents: TanggungJawabPK implements Serializable;
    
    private static final long TanggungJawabPK.serialVersionUID = 1L;
    
}
